name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write # Required to push to GHCR
      contents: read # Required to read the repository contents

    steps:
    # Step 1: Checkout code
    - name: Checkout repository code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx to enable using Docker CLI
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # GitHub actor (the user or bot triggering the action)
        password: ${{ secrets.GITHUB_TOKEN }} # GitHub-provided token automatically available in workflows

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/energy-app:latest .

    # Step 5: Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/energy-app:latest
